### PR TITLE
Added Logging System.

### PR DESCRIPTION
**Pull request by GoldExplosion**

### CODE REVIEW

**Comment by andreped** [comment]
Oh, didn't see that you made a PR, @GoldExplosion. Great! I will look at this after work. However, from briefly looking at it. It looks great!

If you have time, you could work on the other issues we discussed, if you'd like. Just be sure to do it on a separate branch (sync'd with master).

**Comment by GoldExplosion** [comment]
Ok got it, Thanks!

> Just be sure to do it on a separate branch (sync'd with master) 
Sorry to ask this beginner question but I'm not sure what this means. I made a separate branch on my fork but couldn't merge with the dev branch of your repo. I couldn't create a branch in the repo either. If you could tell me more detail on what exactly you want I will follow that. Thank you :)

**Review by andreped — APPROVED** [review]
LGTM. I will merge this and test if it works the way I think. If we find any suboptimal stuff, we can just make an edit. Great job!

**Comment by andreped** [comment]
> Sorry to ask this beginner question but I'm not sure what this means. I made a separate branch on my fork but couldn't merge with the dev branch of your repo. I couldn't create a branch in the repo either. If you could tell me more detail on what exactly you want I will follow that. Thank you :)

Oh, so whenever you are contributing to a project, we work with forks. For each contribution you will have to make a pull request. When making edits, the most optimal way is to make a separate branch where you make the edits (different from master/main) and then you make a PR to merge the edits with the master (and not your master in the fork, but rather upstream - the main repo).

If you were to make edits in your master branch, or in a dev branch, you then make a PR. All is good. However, suddenly, you find that you want to make a new PR, on a different topic. But now, if you make commits to the same branch (as for the previous PR), the same commits will be made for both PRs. That is suboptimal.

Now, lets assume that you have already an existing branch `dev` where you made your first edits. If you now wish to make a new branch `other-stuff`, you have to be careful. If you do `git checkout -b other-stuff` from the `dev` branch, the same edits from `dev` will be carried over. As before, if you now make a PR from the new branch, you will have the same edits as before.

The best way of doing it is for each PR, have one or multiple branches where you work on. It is common to delete these after a PR, or when you find them redundant. Long living branches are rarely a good idea. However having a `dev` branch is quite common.

After you have done your edits in `dev`, go back to `master` by `git checkout master`, and then do `git checkout -b other-stuff`. That way, you will make edits from the original version. And the edits between the two branches won't overlap or have the same proposed edits (in a way). Note that when stuff have been merged (if I have accepted one of your PRs), you can syncronize **(sync)** your master branch (or any other branch really with upstream (my repo)) by simply clicking the `sync fork` button on github (under neath of `clone` button).

That way you are always up to date on the latest changes in upstream, and you can seemlessly contribute and hopefully avoid lots of merge conflicts and other fun stuff. Hope this was a little helpful. Please, just let me know if you have any other questions. Always happy to help :]

And great job on the PR! Will test this tomorrow. Quite long day at work today...

**Comment by GoldExplosion** [comment]
> > Sorry to ask this beginner question but I'm not sure what this means. I made a separate branch on my fork but couldn't merge with the dev branch of your repo. I couldn't create a branch in the repo either. If you could tell me more detail on what exactly you want I will follow that. Thank you :)
> 
> Oh, so whenever you are contributing to a project, we work with forks. For each contribution you will have to make a pull request. When making edits, the most optimal way is to make a separate branch where you make the edits (different from master/main) and then you make a PR to merge the edits with the master (and not your master in the fork, but rather upstream - the main repo).
> 
> If you were to make edits in your master branch, or in a dev branch, you then make a PR. All is good. However, suddenly, you find that you want to make a new PR, on a different topic. But now, if you make commits to the same branch (as for the previous PR), the same commits will be made for both PRs. That is suboptimal.
> 
> Now, lets assume that you have already an existing branch `dev` where you made your first edits. If you now wish to make a new branch `other-stuff`, you have to be careful. If you do `git checkout -b other-stuff` from the `dev` branch, the same edits from `dev` will be carried over. As before, if you now make a PR from the new branch, you will have the same edits as before.
> 
> The best way of doing it is for each PR, have one or multiple branches where you work on. It is common to delete these after a PR, or when you find them redundant. Long living branches are rarely a good idea. However having a `dev` branch is quite common.
> 
> After you have done your edits in `dev`, go back to `master` by `git checkout master`, and then do `git checkout -b other-stuff`. That way, you will make edits from the original version. And the edits between the two branches won't overlap or have the same proposed edits (in a way). Note that when stuff have been merged (if I have accepted one of your PRs), you can syncronize **(sync)** your master branch (or any other branch really with upstream (my repo)) by simply clicking the `sync fork` button on github (under neath of `clone` button).
> 
> That way you are always up to date on the latest changes in upstream, and you can seemlessly contribute and hopefully avoid lots of merge conflicts and other fun stuff. Hope this was a little helpful. Please, just let me know if you have any other questions. Always happy to help :]
> 
> And great job on the PR! Will test this tomorrow. Quite long day at work today...

Thank you for taking the time to reply. I understood perfectly. Very helpful!!. Have a nice day :)

**Pull request merged**
