### PR TITLE
fix paw icon

### PR DESCRIPTION
**Pull request by MasonLyons**

### CODE REVIEW

**Review by andreped — CHANGES_REQUESTED** [review]
Thank you for the PR, @MasonLyons! The updated image looks to be of suitable size and format.

However, I think in order to change style, which seems required now as discussed in https://github.com/andreped/super-ml-pets/issues/61#issuecomment-1761084503, we really should change all templates in a bunch, instead of a few here-and-there.

Are you interested in doing that transfer?

**Comment by MasonLyons** [comment]
> Thank you for the PR, @MasonLyons! The updated image looks to be of suitable size and format.
> 
> However, I think in order to change style, which seems required now as discussed in https://github.com/andreped/super-ml-pets/issues/61#issuecomment-1761084503, we really should change all templates in a bunch, instead of a few here-and-there.
> 
> Are you interested in doing that transfer?

Unfortunatly I've only just started playing the game so I'm not 100% sure I'd be able to do it but I can take a go at it.

I'd need to first fix the dynamic scaling issue so I can more easily get the new screenshots.

I've found the best way to do it is to make a script which runs the image recognition functions but also saves the output. This means the new images are perfectly sizes and in the correct format.

**Comment by andreped** [comment]
> Unfortunatly I've only just started playing the game so I'm not 100% sure I'd be able to do it but I can take a go at it.

The change you just did I would approve. If you do the same for the other pets and items, you can update the PR and I can review it. And yes, great that you are doing it in a standardised way. That will make it easier to do it for the rest of the items as well :]

Just update your branch when it is done, that way the PR will be updated. Then you can ask me to review it again.

**Comment by andreped** [comment]
I have updated **all** icons now, so this PR is no longer needed.

CV capturing system works, but the game logic has changed quite a bit, so it needs some work, but should be close.

**Pull request closed without merging**
